import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-3xl font-bold'>Next Github Test</h1>
      <h1 className='text-3xl font-bold'>Testing a push</h1>
    </div>
  );
}
